# fly.toml app configuration file generated for recognition on 2026-06-10T00:26:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'recognition'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
