"""Turn catalogue.csv (from build_manifest.py) into idempotent SQL that ingests
the model's label space into the `cars` table, with a first-pass rarity tier.

    python ingest_catalogue.py --catalogue out/catalogue.csv --out catalogue_insert.sql

Run 0003_catalogue_columns.sql first, then paste the generated SQL into the
Supabase SQL editor (or psql). Upserts on model_class, so it's safe to re-run
after retraining.

Rarity is a heuristic first pass (brand prestige + body + production rarity);
tune `rarity_tier()` or move to dynamic rarity (catch frequency) later.
"""
from __future__ import annotations

import argparse

import pandas as pd

# Brand prestige buckets (lowercased).
EXOTIC = {
    "ferrari", "lamborghini", "mclaren", "bugatti", "pagani", "koenigsegg",
    "maserati", "aston martin",
}
LUXURY = {
    "porsche", "rolls-royce", "bentley", "jaguar", "lotus", "alfa romeo",
    "mercedes-amg", "maybach",
}
SPORTY_BODY = {"sports", "coupe", "convertible"}

TIERS = ["common", "uncommon", "rare", "epic", "legendary"]


def rarity_tier(make: str, body: str, y0, y1) -> str:
    score = 0
    m = (make or "").lower()
    if m in EXOTIC:
        score += 4
    elif m in LUXURY:
        score += 2
    if body in SPORTY_BODY:
        score += 1
    try:
        if y0 and y1 and (int(y1) - int(y0)) <= 3:  # short production run
            score += 1
    except (TypeError, ValueError):
        pass
    try:
        if y0 and int(y0) < 1975:                    # vintage
            score += 1
    except (TypeError, ValueError):
        pass

    if score >= 5:
        return "legendary"
    if score == 4:
        return "epic"
    if score == 3:
        return "rare"
    if score >= 1:
        return "uncommon"
    return "common"


def sql_str(v, maxlen: int | None = None) -> str:
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return "NULL"
    s = str(v).replace("\r", " ").replace("\n", " ").strip()
    if maxlen and len(s) > maxlen:
        s = s[: maxlen - 1].rstrip() + "…"
    return "'" + s.replace("'", "''") + "'"


def sql_year(v) -> str:
    try:
        if pd.isna(v):
            return "NULL"
    except (TypeError, ValueError):
        pass
    try:
        return str(int(v))
    except (TypeError, ValueError):
        return "NULL"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalogue", required=True)
    ap.add_argument("--out", default="catalogue_insert.sql")
    args = ap.parse_args()

    df = pd.read_csv(args.catalogue)
    lines = [
        "-- Generated by ingest_catalogue.py — run 0003_catalogue_columns.sql first.",
        "-- Upserts on model_class; safe to re-run.",
        "",
    ]

    cols = ("make, model, generation, year_start, year_end, body, rarity_tier, "
            "segment, description, engine, variant, model_class")
    skipped = 0
    for _, r in df.iterrows():
        def cell(key: str) -> str:
            v = r.get(key)
            return "" if (v is None or (isinstance(v, float) and pd.isna(v))) else str(v).strip()

        make, model = cell("make"), cell("model")
        if not make or not model:
            # Unmatched folder (no CSV row) — can't form a valid cars entry
            # (make/model are NOT NULL). Skip; fix the join + re-run if many.
            skipped += 1
            continue

        tier = rarity_tier(make, str(r.get("body", "other")),
                           r.get("year_start"), r.get("year_end"))
        body = cell("body") or "other"
        values = ", ".join([
            sql_str(make),
            sql_str(model),
            "NULL",                                  # generation (variant-level dataset)
            sql_year(r.get("year_start")),
            sql_year(r.get("year_end")),
            sql_str(body),
            f"'{tier}'",
            sql_str(r.get("segment")),
            sql_str(r.get("description"), maxlen=600),
            sql_str(r.get("engine")),
            sql_str(r.get("variant")),
            sql_str(r.get("model_class")),
        ])
        lines.append(
            f"insert into cars ({cols})\nvalues ({values})\n"
            "on conflict (model_class) do update set\n"
            "  make=excluded.make, model=excluded.model, year_start=excluded.year_start,\n"
            "  year_end=excluded.year_end, body=excluded.body, rarity_tier=excluded.rarity_tier,\n"
            "  segment=excluded.segment, description=excluded.description,\n"
            "  engine=excluded.engine, variant=excluded.variant;"
        )

    # Placeholder sprite per car (real art is non-blocking).
    lines += [
        "",
        "insert into sprites (car_id, asset_url, is_current)",
        "select c.id, '/sprites/placeholder/' || c.id || '.png', true",
        "from cars c",
        "where not exists (select 1 from sprites s where s.car_id = c.id and s.is_current);",
        "",
    ]

    with open(args.out, "w") as f:
        f.write("\n".join(lines))

    # Distribution summary.
    tiers = df.apply(
        lambda r: rarity_tier(r.get("make", ""), str(r.get("body", "other")),
                              r.get("year_start"), r.get("year_end")),
        axis=1,
    ).value_counts()
    print(f"rows: {len(df)} ingested: {len(df) - skipped} skipped(no make/model): {skipped} -> {args.out}")
    for t in TIERS:
        print(f"  {t:10s} {int(tiers.get(t, 0))}")


if __name__ == "__main__":
    main()
